import { PortfolioSkills } from "@/lib/types";

export const Skills: PortfolioSkills[] = [
  { label: "React", icon: "/images/simpleicons/react.svg" },
  { label: "Next.js", icon: "/images/simpleicons/nextdotjs.svg" },
  { label: "Nuxt.js", icon: "/images/simpleicons/nuxt.svg" },
  { label: "Vue", icon: "/images/simpleicons/vuedotjs.svg" },
  { label: "Expo", icon: "/images/simpleicons/expo.svg" },
  { label: "TypeScript", icon: "/images/simpleicons/typescript.svg" },
  { label: "GraphQL", icon: "/images/simpleicons/graphql.svg" },
  { label: "Golang", icon: "/images/simpleicons/go.svg" },
  { label: "Java", icon: "/images/simpleicons/java.svg" },
  { label: "Node.js", icon: "/images/simpleicons/nodedotjs.svg" },
  { label: "Express", icon: "/images/simpleicons/express.svg" },
  { label: "NestJS", icon: "/images/simpleicons/nestjs.svg" },
  { label: "Python", icon: "/images/simpleicons/python.svg" },
  { label: "FastAPI", icon: "/images/simpleicons/fastapi.svg" },
  { label: "Spring Boot", icon: "/images/simpleicons/springboot.svg" },
  { label: "ASP.NET", icon: "/images/simpleicons/dotnet.svg" },
  { label: "PostgreSQL", icon: "/images/simpleicons/postgresql.svg" },
  { label: "MongoDB", icon: "/images/simpleicons/mongodb.svg" },
  { label: "Solidity", icon: "/images/simpleicons/solidity.svg" },
  { label: "Fastify", icon: "/images/simpleicons/fastify.svg" },
  { label: "Prisma", icon: "/images/simpleicons/prisma.svg" },
  { label: "Drizzle", icon: "/images/simpleicons/drizzle.svg" },
  { label: "Sequelize", icon: "/images/simpleicons/sequelize.svg" },
  { label: "Laravel", icon: "/images/simpleicons/laravel.svg" },
  { label: "MySQL", icon: "/images/simpleicons/mysql.svg" },
  { label: "Hibernate", icon: "/images/simpleicons/hibernate.svg" },
  { label: "Docker", icon: "/images/simpleicons/docker.svg" },
  { label: "Terraform", icon: "/images/simpleicons/terraform.svg" },
];
